### ISSUE TITLE
Knitr and inline equations

### ISSUE THREAD

**Issue by amandawarlick** [nwfsc-timeseries/atsa-labs#1]
I know you said not to fuss with markdown, but I'd like some help debugging what's going on here. 

Code, copy-pasted from the lab Rmd file.
Using Form 1 $\yy=\ZZ\xx+\ee$, write out the model, showing the $\ZZ$ and $\xx$ matrices, being fit by this command.

The inline equations are not knitting properly, and it happens if I just knit the lab Rmd file, so I assume it must be a setting I have or a package that isn't loaded?
<img width="785" alt="screen shot 2019-01-14 at 7 36 05 am" src="https://user-images.githubusercontent.com/15167059/51122874-b7278380-17cf-11e9-97bd-461fdc27b911.png">

Thanks!

**Comment by mdscheuerell** [comment]
Sorry @amandawarlick--just seeing this now.

The `\??` are LaTex shortcuts that @eeholmes used so she didn't have to type things out longhand like

`\mathbf{y} = \mathbf{Z} \mathbf{x} + \mathbf{e}`

to render

__y__ = __Z__ __x__ + __e__.

They are defined in another file that appears to be missing here.

**Comment by amandawarlick** [comment]
Ah yes yes - thanks!  I figured it was something silly. I'm comfortable with markdown but relatively newer to equations and Latex.
