### ISSUE TITLE
Problems chapter 1.7 fix.

### ISSUE THREAD

**Issue by Danahi** [nwfsc-timeseries/atsa-labs#13]
Problem 1.7.1 states "Build a 4×3 matrix with the numbers 1 through 4 in each row."

But it should be one of the following options:
"Build a 4×3 matrix with the numbers 1 through 4 in each **column**."
**or**
"Build a **3×4** matrix with the numbers 1 through 4 in each row."

**Comment by Danahi** [comment]
The same counts for question 3:
"Build a 4×3 matrix with the numbers 1 through 12 by row (meaning the first row will have the numbers 1 through 4 in it)."
should be:
"Build a 4×3 matrix with the numbers 1 through 12 by row (meaning the first row will have the numbers 1 through **3** in it)."
**or**
"Build a **3×4** matrix with the numbers 1 through 12 by row (meaning the first row will have the numbers 1 through 4 in it)."

**Comment by Danahi** [comment]
Question 16:
What should the other locations have for values? 0 or their original value?
It may be good to display the expected resulting matrix there.

**Comment by ericward-noaa** [comment]
@Danahi Thanks for catching these errors! I just updated the examples and incorporated your changes. 

For 16, the B matrix should be a 3x3 matrix, with B[1,1], B[2,3] and B[3,2] = 1, with the rest of the elements = 0
