### ISSUE TITLE
Problem Chapter 12 fix.

### ISSUE THREAD

**Issue by yulisong** [nwfsc-timeseries/atsa-labs#16]
Hi, thank you for sharing such a great lecture note, it really helps me understanding the JAGS model. But I've got two questions here. 

1. Chapter 12.3 “**tau.cor <- tau.obs / (1-phi*phi)**”: After drawing the DAG and considering the context, I think it should be "**tau.cor <- tau.obs * (1-phi*phi)**".
2. Chapter 12.4 "**E[y_t] = y_{t-1} + e_{t-1}**": As the expectation of y_t is a constant, I think maybe it's better to change it to be "**E[y_t] = y_{t-1}**" and "**y_t = y_{t-1} + e_{t-1}**".

Thank you again for providing such a clear note and good examples!

**Comment by eeholmes** [comment]
Thanks for catching that! We have done a variety of updates on the JAGS chapter and incorporated that correction in.

--Eli
