### ISSUE TITLE
Typo in priors

### ISSUE THREAD

**Issue by ericward-noaa** [nwfsc-timeseries/atsa-labs#18]
RPK caught this prior notation that needs to be changed:

https://nwfsc-timeseries.github.io/atsa-labs/sec-stan-uss.html

You have the weakly informative prior as x_1 ~ N(0, 0.01), but I think you mean N(0, 10).  

(And also, in the HTML it is called x_1, but in the stan code itself, the parameter is called x0; not sure if that matters or not).

**Comment by eeholmes** [comment]
Fixed. Along with the broken negative binomial example in the JAGS chapter. 5a6ec5c74e94fc27e68f86a14d6d84dd73c43189
