### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by marksorel8** [nwfsc-timeseries/atsa-labs#2]
@eeholmes @mdscheuerell  Is the assignment that you wanted us take a look at for tomorrow the problems at the end of chapter 4 in the lab book?

**Comment by mdscheuerell** [comment]
@marksorel8 Yes, the 6 Q's in Sec 4.11 re the experimental phytoplankton data.

**Comment by marksorel8** [comment]
Great! That's what I thought but just wanted to double check.
