### ISSUE TITLE
big picture questions

### ISSUE THREAD

**Issue by amandawarlick** [nwfsc-timeseries/atsa-labs#3]
I might be the only one having these questions, and if that's the case, I apologize, but after mostly working through the homework questions, I'm realizing I have a few big-picture gaps in my understanding that I'm hoping we can spend a few minutes reviewing in lecture. 

Mainly, I'm missing the link between fitting arima models, determining the model order, getting parameters, and then interpreting what the model orders and parameters mean for a plain-language statement about whatever trend we're observing.  For example, when we see that our best model is (1,2,3) or (2,1,2) with a seasonal lag, what do we say about the overall trend in landings? And what is the interpretation of the ar/ma parameter estimates? Or is it less about making a statement about the observed trend and more about predicting forward? Or both? 

Admittedly I'm only caught up on about half of last week's reading, so maybe that would help, but thanks!

**Comment by mdscheuerell** [comment]
@amandawarlick These are good Q's. The interpretation of the AR & MA coefficients can be a tricky, indeed. The AR coefs are easier to interpret, especially if we're talking about biological processes, or cause-effect interactions. The MA coefs are simply weights of errors past, and tend to have very little meaning other than the literal translation (eg, if MA_1 = 0.8 and MA_2 = 0.4, then a mistake (error) 1 time step ago has twice the influence of an error 2 time steps ago).

Time series analysis is (usually) equally concerned with understanding past patterns and predicting outcomes for the future. It is important to have a model that explains past data well if one is to be confident in any forecasts. Contemporary/historical analysis also helps us gain insights into causal mechanisms.

**Comment by amandawarlick** [comment]
Thanks for this!
