### ISSUE TITLE
DLM HW Problems 3 & 4

### ISSUE THREAD

**Issue by marksorel8** [nwfsc-timeseries/atsa-labs#6]
The fitted process variance of the coefficients for PDO are 0.00. It seems really unlikely that this would be the "best fit" value, and of course the fits to the data don't look good.  Any idea what I could be doing wrong? Happy to post code here or email it.

**Comment by mfeddern** [comment]
I am having the same issue!

**Comment by mdscheuerell** [comment]
@marksorel8 @mfeddern Yes, it is entirely possible that the data support for a time-varying slope is negligible, and thus the process error could be 0. And yes, the fits to stock-recruit models can be pretty lousy a well.
