### ISSUE TITLE
Two quick (project-related) questions

### ISSUE THREAD

**Issue by amandawarlick** [nwfsc-timeseries/atsa-labs#7]
1. I'm trying to use my own data in the linear filtering example, and was wondering if there was a clever way to implement the code in 3.6 in a multi-variate example. What if we wanted to look at the trends for air passengers and train passengers side-by-side?

2. What would be the best way to systematically test the best lag times for covariates? My project is on monthly marine mammal strandings and oceanographic conditions, and I have looked at glm models with some of these data, but I don't have a sense for how to test different lag times for ocean covariates. Maybe once I honed in on significant predictors using glm(), I could then put those into a marss() model and look at AIC values for different lag times? Would the ccf examples of the lynx and sun spots help me with this?

Happy to hold my questions for in-person if the answer is more involved.

Thanks!

**Comment by mdscheuerell** [comment]
@amandawarlick 

1) To clarify: do you want to estimate a common trend among the 2+ time series, or you want to do each ts separately? Is your intent of the linear filtering to remove a trend from the data? If so, I'd suggest some of the other methods we've used in class along the lines of a dummy covariate (eg, fixed effect or sine/cosine).

2) I _do not_ recommend selecting your covariates, and/or lags, based on first fitting GLMs (or other models). You would be best served by stating explicitly all of the possible combos, fitting them in MARSS, and then evaluating AICc. Note, too, that any covariates that are themselves correlated are likely to have similar estimates of AICc.

**Comment by amandawarlick** [comment]
Great, got it - makes sense. 

Thanks!
