### ISSUE TITLE
plotting/formatting question

### ISSUE THREAD

**Issue by amandawarlick** [nwfsc-timeseries/atsa-labs#8]
Sort of a stupid question... Do the four-layer decomposition plots not clump together? In other words, this code doesn't work - the plots all pop up independently rather than in a 2x2 grid.

par(mfrow = c(2,2), oma=c(0,0,0,0), mar=c(1,1,1,1))
plot <- plot(decomp_hs, yax.flip = TRUE, xlab = 'Harbor seal')
plot <- plot(decomp_csl, yax.flip = TRUE, xlab = 'California sea lion')
plot <- plot(decomp_ssl, yax.flip = TRUE, xlab = 'Steller sea lion')
plot <- plot(decomp_sp_cet, yax.flip = TRUE, xlab = 'Dalls porpoise')

Thanks!

**Comment by mdscheuerell** [comment]
I doubt it will work to do what you're trying because the plot method for `decomp()` presumably already sets something like `par(mfrow = c(4, 1), ...)`.

**Comment by amandawarlick** [comment]
Yep, got it - thanks!
